title: Students Defending Democracy
subheads:
    - "Students Defending democracy against fascist attacks on our public schools"

email: false
description: >-
    Students Defending democracy against fascist attacks on our public schools
baseurl: ""
url: "https://studentsdefendingdemocracy.org/"

# uncomment and fill in any social IDs you want linked from the top of your page

#email: "info@defenseofdemocracy.org"
# telephone_number: "999-999-9999"
# bluesky_username: "my_bluesky_username"
# cashapp_username: "my_cashapp_username"
# discord_username: "my_discord_username"
# github_username: "my_github_username"
instagram_username: "studentsdefendingdemocracy"
# mastodon_username: "@username@example.host"
# pinterest_username: "my_pinterest_username"
# threads_username: "my_threads_username"
tiktok_username: "studentsdefdem"
# venmo_username: "my_venmo_username"
# youtube_username: "my_youtube_username"

# uncomment for plausible.io analytics, should match the "url" above
plausible_io: studentsdefendingdemocracy.org

# uncomment to add your google analytics
# google_analytics: UA-NNNNNNNN-N

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

exclude:
    - VERSION
    - bin
    - linky.gemspec
    - netlify.toml
    - scripts

linky:
    body_background: "#3e76cd"
    body_foreground: "#F0F0F0"
    button_background: "#f79621"
    button_foreground: "#000"
    social_button_color: "#ffffff"

collections:
    - links

# tell the jekyll-feed plugin to include the links collection
feed:
    collections:
        - links
